services:
  hotel.webapi:
    image: hotel.webapi
    build:
      context: .
      dockerfile: Hotel/src/Hotel.WebApi/Dockerfile
    networks:
      - hotel-network

  hotel.db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nerdekalnoktacom123!.
    ports:
      - '3366:3306'
    volumes:
      - hotel-db:/var/lib/mysql
    networks:
      - hotel-network

  raport.webapi:
    image: raport.webapi
    build:
      context: .
      dockerfile: Raport/src/Raport.WebApi/Dockerfile
      
  raport.db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: neredekalcomuser
      POSTGRES_PASSWORD: nerdekalnoktacom123!.
      POSTGRES_DB: nerdekaldb
    volumes:
      - report-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - 5431:5432
    networks:
      - report-network

volumes:
  hotel-db:
  report-db:
networks:
  hotel-network:
  report-network: